export const ENTITLEMENT_STATUS_ACTIVE = 4;
export const ENTITLEMENT_STATUS_TRIAL = 3;
export const ENTITLEMENT_STATUS_GRACE = 2;
export const ENTITLEMENT_STATUS_CANCEL = 1;
export const ENTITLEMENT_STATUS_FREE = 0;
export const ENTITLEMENT_STATUS_SUSPEND = -1;
export const ENTITLEMENT_STATUS_CHURN = -2;
export const ENTITLEMENT_STATUS_REFUND = -3;
