export const EVENT_AUTO_DISMISS_DURATION = 5000;
export const NETWORK_STATUS_DEBOUNCE_DURATION = 1000;

export const EVENT_TYPE_INFO = 'EVENT_TYPE_INFO';
export const EVENT_TYPE_WARNING = 'EVENT_TYPE_WARNING';
export const EVENT_TYPE_SUCCESS = 'EVENT_TYPE_SUCCESS';
export const EVENT_TYPE_ERROR = 'EVENT_TYPE_ERROR';
