import React from 'react';
import MainTab from './MainTab';
import {
  CrossTrainingScreen,
  ExerciseScreen,
  ExerciseRepsScreen,
  FinishWorkoutScreen,
  LatestCommentsScreen,
  LatestNotesScreen,
  LeaderboardScreen,
  LearningVideoScreen,
  LearningScreen,
  NewScheduleScreen,
  NotesScreen,
  NotificationsScreen,
  PlanScreen,
  ProfileScreen,
  ProgramScreen,
  ProgramsScreen,
  RepliesScreen,
  RewardMenuScreen,
  SettingsScreen,
  StatsGraphScreen,
  TeamScreen,
  TodayWorkoutsScreen,
  TrainingScreen,
  WorkoutScreen,
  WriteNoteScreen,
  CourseScreen,
  SubscribeToPlanScreen,
  NewCourseScreen,
  NewWorkoutScreen,
  NewProgramScreen,
  PaywallScreen_Legacy,
  PositionScreen,
  ImprovementScreen,
  DailyGoalScreen,
  CreatingPlanScreen,
  RecommendationSettingsScreen,
  RecommendationsScreen,
  ContactScreen,
  PaymentSuccessScreen,
  BrowseCollectionScreen,
} from '../../screens';

const getAppScreens = (Stack) => {
  return (
    <>
      <Stack.Screen
        name="Main"
        component={MainTab}
        options={MainTab.navigationOptions}
      />
      {/* Soon to be removed */}
      <Stack.Screen
        name="Calendar"
        component={MainTab}
        options={MainTab.navigationOptions}
      />
      <Stack.Screen
        name="Settings"
        component={SettingsScreen}
        options={SettingsScreen.navigationOptions}
      />
      <Stack.Screen
        name="Profile"
        component={ProfileScreen}
        options={ProfileScreen.navigationOptions}
      />
      {/* Soon to be removed */}
      <Stack.Screen
        name="Program"
        component={ProgramScreen}
        options={ProgramScreen.navigationOptions}
      />
      {/* Soon to be removed */}
      <Stack.Screen
        name="Programs"
        component={ProgramsScreen}
        options={ProgramsScreen.navigationOptions}
      />
      <Stack.Screen
        name="ViewProgram"
        component={NewProgramScreen}
        options={NewProgramScreen.navigationOptions}
      />
      {/* Soon to be removed */}
      <Stack.Screen
        name="Workout"
        component={WorkoutScreen}
        options={WorkoutScreen.navigationOptions}
      />
      <Stack.Screen
        name="ViewWorkout"
        component={NewWorkoutScreen}
        options={NewWorkoutScreen.navigationOptions}
      />
      {/* Soon to be moved to PerformingStack */}
      <Stack.Screen
        name="Exercise"
        component={ExerciseScreen}
        options={ExerciseScreen.navigationOptions}
      />
      {/* Soon to be removed */}
      <Stack.Screen
        name="Course"
        component={CourseScreen}
        options={CourseScreen.navigationOptions}
      />
      <Stack.Screen
        name="ViewCourse"
        component={NewCourseScreen}
        options={NewCourseScreen.navigationOptions}
      />
      {/* Soon to be removed */}
      <Stack.Screen
        name="ExerciseReps"
        component={ExerciseRepsScreen}
        options={ExerciseRepsScreen.navigationOptions}
      />
      <Stack.Screen
        name="LearningVideo"
        component={LearningVideoScreen}
        options={LearningVideoScreen.navigationOptions}
      />
      <Stack.Screen
        name="Learning"
        component={LearningScreen}
        options={LearningScreen.navigationOptions}
      />
      <Stack.Screen
        name="FinishWorkout"
        component={FinishWorkoutScreen}
        options={FinishWorkoutScreen.navigationOptions}
      />
      <Stack.Screen
        name="RewardMenu"
        component={RewardMenuScreen}
        options={RewardMenuScreen.navigationOptions}
      />
      <Stack.Screen
        name="Team"
        component={TeamScreen}
        options={TeamScreen.navigationOptions}
      />
      {/* Soon to be removed */}
      <Stack.Screen
        name="Training"
        component={TrainingScreen}
        options={TrainingScreen.navigationOptions}
      />
      <Stack.Screen
        name="NewSchedule"
        component={NewScheduleScreen}
        options={NewScheduleScreen.navigationOptions}
      />
      <Stack.Screen
        name="Notes"
        component={NotesScreen}
        options={NotesScreen.navigationOptions}
      />
      <Stack.Screen
        name="Notifications"
        component={NotificationsScreen}
        options={NotificationsScreen.navigationOptions}
      />
      <Stack.Screen
        name="Plan"
        component={PlanScreen}
        options={PlanScreen.navigationOptions}
      />
      <Stack.Screen
        name="ModifyPlan"
        component={SubscribeToPlanScreen}
        options={SubscribeToPlanScreen.navigationOptions}
      />
      <Stack.Screen
        name="WriteNote"
        component={WriteNoteScreen}
        options={WriteNoteScreen.navigationOptions}
      />
      <Stack.Screen
        name="Replies"
        component={RepliesScreen}
        options={RepliesScreen.navigationOptions}
      />
      {/* Soon to be removed */}
      <Stack.Screen
        name="TodayWorkouts"
        component={TodayWorkoutsScreen}
        options={TodayWorkoutsScreen.navigationOptions}
      />
      <Stack.Screen
        name="Leaderboard"
        component={LeaderboardScreen}
        options={LeaderboardScreen.navigationOptions}
      />
      {/* Soon to be removed */}
      <Stack.Screen
        name="StatsGraph"
        component={StatsGraphScreen}
        options={StatsGraphScreen.navigationOptions}
      />
      {/* Soon to be removed */}
      <Stack.Screen
        name="LatestComments"
        component={LatestCommentsScreen}
        options={LatestCommentsScreen.navigationOptions}
      />
      {/* Soon to be removed */}
      <Stack.Screen
        name="LatestNotes"
        component={LatestNotesScreen}
        options={LatestNotesScreen.navigationOptions}
      />
      <Stack.Screen
        name="Paywall"
        component={PaywallScreen_Legacy}
        options={PaywallScreen_Legacy.navigationOptions}
      />
      <Stack.Screen
        name="PaymentSuccess"
        component={PaymentSuccessScreen}
        options={PaymentSuccessScreen.navigationOptions}
      />
      <Stack.Screen
        name="RecommendationSettings"
        component={RecommendationSettingsScreen}
        options={RecommendationSettingsScreen.navigationOptions}
      />
      <Stack.Screen
        name="Position"
        component={PositionScreen}
        options={PositionScreen.navigationOptions}
      />
      <Stack.Screen
        name="Improvement"
        component={ImprovementScreen}
        options={ImprovementScreen.navigationOptions}
      />
      <Stack.Screen
        name="DailyGoal"
        component={DailyGoalScreen}
        options={DailyGoalScreen.navigationOptions}
      />
      <Stack.Screen
        name="CreatingPlan"
        component={CreatingPlanScreen}
        options={CreatingPlanScreen.navigationOptions}
      />
      <Stack.Screen
        name="Recommendations"
        component={RecommendationsScreen}
        options={RecommendationsScreen.navigationOptions}
      />
      <Stack.Screen
        name="Contact"
        component={ContactScreen}
        options={ContactScreen.navigationOptions}
      />
      <Stack.Screen
        name="CrossTraining"
        component={CrossTrainingScreen}
        options={CrossTrainingScreen.navigationOptions}
      />
      <Stack.Screen
        name="BrowseCollection"
        component={BrowseCollectionScreen}
        options={BrowseCollectionScreen.navigationOptions}
      />
    </>
  );
};

export default getAppScreens;
